# Generated by Django 5.0.7 on 2024-09-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_user_task_complete_task_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='To do', max_length=200),
        ),
    ]
