# Generated by Django 5.0.7 on 2024-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not Started', max_length=200),
        ),
    ]
